# Generated by Django 3.0.3 on 2020-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App8Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'app8_user',
            },
        ),
    ]
