# Generated by Django 3.0.3 on 2020-03-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App8Users',
        ),
    ]
