# Generated by Django 3.0.3 on 2020-03-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app14', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
