# Generated by Django 3.0.3 on 2020-03-02 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0003_formbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormUser2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('pwssword', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[35678]\\d{9}', message='请输入一个手机号码')])),
            ],
            options={
                'db_table': 'form_user2',
            },
        ),
        migrations.AlterField(
            model_name='formbook',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(limit_value=1000)]),
        ),
    ]
