# Generated by Django 3.0.3 on 2020-02-24 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('authot', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'orm_book',
            },
        ),
        migrations.CreateModel(
            name='ORMCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'orm_category',
            },
        ),
        migrations.CreateModel(
            name='ORMArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.ORMCategory')),
            ],
            options={
                'db_table': 'orm_article',
                'ordering': ['-created', 'id'],
            },
        ),
    ]
