# Generated by Django 3.0.3 on 2020-02-25 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_ormcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORMFrontUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'orm_front',
            },
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app3.ORMFrontUser')),
            ],
            options={
                'db_table': 'orm_user_ext',
            },
        ),
    ]
