# Generated by Django 3.0.3 on 2020-02-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_auto_20200226_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'filter_article',
            },
        ),
    ]
