# Generated by Django 3.0.3 on 2020-02-26 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0007_filterarticle_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'filter_author',
            },
        ),
        migrations.CreateModel(
            name='FilterBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('page', models.IntegerField()),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.FilterAuthor')),
            ],
            options={
                'db_table': 'filter_book',
            },
        ),
        migrations.CreateModel(
            name='FilterPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'filter_publish',
            },
        ),
        migrations.CreateModel(
            name='FilterBookOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.FilterBook')),
            ],
            options={
                'db_table': 'filter_book_order',
            },
        ),
        migrations.AddField(
            model_name='filterbook',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.FilterPublish'),
        ),
    ]
