# Generated by Django 3.0.3 on 2020-03-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'app6_file',
            },
        ),
    ]
