# Generated by Django 3.0.3 on 2020-03-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upfiles',
            name='file',
            field=models.FileField(upload_to='', verbose_name='app6/files'),
        ),
    ]
